simple_clone/simple_clone/posts/urls.py
from django.urls import path, re_path

from . import views

app_name = "posts"

urlpatterns = [
    re_path(r"^$", views.PostList.as_view(), name="all"),
    re_path(r"new/$", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)", views.UserPosts.as_view(), name="for_user"),
    re_path(
        r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.PostDetail.as_view(),
        name="single",
    ),
    re_path(r"delete/(?P<pk>\d+)/$", views.DeletePost.as_view(), name="delete"),
]

simple_clone/simple_clone/simple_clone/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path

from simple_clone.views import HomePage, TestPage, ThanksPage

urlpatterns = [
    path("admin/", admin.site.urls),
    re_path("^$", HomePage.as_view(), name="home"),
    re_path(r"^accounts/", include("accounts.urls", namespace="accounts")),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),  # uses inbuilt auth
    re_path(
        r"^test/", TestPage.as_view(template_name="test.html"), name="test"
    ),  # uses inbuilt auth
    re_path(r"^thanks/", ThanksPage.as_view(), name="thanks"),  # uses inbuilt auth
    re_path(r"^posts/", include("posts.urls", namespace="posts")),
    re_path(r"^groups/", include("groups.urls", namespace="groups")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [re_path(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

simple_clone/simple_clone/posts/models.py
from email import message

import markdown
from django.conf import Settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

# Create your models here.
from groups.models import Group

User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(
        Group, related_name="posts", null=True, blank=True, on_delete=models.CASCADE
    )

    def __str__(self) -> str:
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = markdown.markdown(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "post:single", kwargs={"username": self.user.username, "pk": self.pk}
        )

    class Meta:
        # - below indicates descending order
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

simple_clone/simple_clone/posts/views.py
from typing import Any, Dict

from braces.views import SelectRelatedMixin
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic

# from forms import *
# from models import *
from . import forms, models

# Create your views here.


User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")


class UserPosts(generic.ListView):
    model = models.Post

    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DateDetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        query_set = super().get_queryset()
        return query_set.filter(user__username__iexact=self.kwargs.get("username"))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ("message", "group")
    model = models.Post

    def form_invalid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        query_set = super().get_queryset()
        return query_set.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

simple_clone/simple_clone/posts/templates/posts/_post.html
<div class="post media">
    <h3>{{ post.message_html|safe }}</h3>
    <div class="media-body">
        <h5 class="media-heading">
            <span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">i@{{post.user.username{{</a></span>
            <div class="time">
                <a href="{% url 'posts:single' username=post.user.username pk=posts.pl %}"></a>
            </div>
        </h5>
    </div>
    <div class="media-footer">
        {% if user.is_authenticated and post.user == user %}
            <a href="{% url 'posts:delete' pk=post.pk %}"
               title="delete"
               class="btn btn-primary">Delete posts</a>
        {% endif %}
    </div>
</div>

simple_clone/simple_clone/posts/templates/posts/post_base.html
{% extends 'base.html' %}
{% block content %}
    <div class="posts-page">
        <div class="container">
            <div class="row">
                {% block prepost %}
                {% endblock prepost %}
                {% block post_content %}
                {% endblock post_content %}
                {% block post_post %}
                {% endblock post_post %}
            </div>
        </div>
    </div>
{% endblock content %}

simple_clone/simple_clone/posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
    <h3>Are you sure you want to delet this posts</h3>
    <div class="posts">{% include "posts/_post.html" with post=object hide_delete=True %}</div>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="confirm delete" class="btn btn-warning" />
        <a href="{% url 'posts:single' username-username pk=objects.pk %}"
           class="btn btn-primary">Cancel</a>
    </form>
{% endblock post_content %}

simple_clone/simple_clone/posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
    <div class="col-md-8">{% include "posts/_post.html" %}</div>
{% endblock post_content %}

simple_clone/simple_clone/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load django_bootstrap5 %}
{% block post_content %}
    <h4>Create a new post</h4>
    <form id="postForm" method="post" action:"{% url 'posts:create' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="post" />
    </form>
{% endblock post_content %}

simple_clone/simple_clone/posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}
{% block pre_post_content %}
    <div class="col-md-4">
        {% if request.user.is_authenticated %}
            <div class="card card-with-shadow">
                <div class="content">
                    <h5 class="title">Your Groups</h5>
                    <ul class="list-unstyled">
                        {% for member_group in get_user_groups %}
                            <li class="group li-with-bullet">
                                <a href="{% url 'groups:single' slug=member_group.group.slug %}">li</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        <div class="card card-with-shadow">
            <div class="content">
                <h5 class="title">All Groups</h5>
                <ul class="list-unstyled">
                    {% for other_group in get_other_groups %}
                        <li class="group li-with-bullet">
                            <a href="{% url 'groups:single' slug=other_group.slug %}"></a>oli
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock pre_post_content %}
{% block post_content %}
    <div class="col-md-8">
        {% for post in post_list %}
            {% include "posts/_post.html" %}
        {% endfor %}
    </div>
{% endblock post_content %}

simple_clone/simple_clone/posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}
{% block prepost %}
    <div class="col-md-4">
        <h1>@{{ post_user.username }}</h1>
    </div>
{% endblock prepost %}
{% block post_content %}
    <div class="col-md-8">
        {% for post in post_list %}
            {% include "posts/_posts.html" %}
        {% endfor %}
    </div>
{% endblock post_content %}