advanced_section/class_based_views/CBV_APP/urls.py
from CBV_APP import views
from django.urls import path, re_path

app_name = "CBV_APP"

urlpatterns = [
    path("", views.SchoolListView.as_view(), name="list"),
    re_path(r"^(?P<pk>\d+)/$", views.SchoolDetailView.as_view(), name="detail"),
    re_path(r"^create/$", views.SchoolCreateView.as_view(), name="create"),
    re_path(r"^update/(?P<pk>\d+)/$", views.SchoolUpdateView.as_view(), name="update"),
    re_path(r"^delete/(?P<pk>\d+)/$", views.SchoolDeleteView.as_view(), name="delete"),
]

advanced_section/class_based_views/class_based_views/urls.py
from CBV_APP import views
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("admin/", admin.site.urls),
    # re_path(r"^$", views.index),  # function based view
    # re_path(r"^$", views.CBView.as_view()),  # CBV version
    re_path(r"^$", views.IndexView.as_view()),  # CBV version
    path(r"CBV_APP/", include("CBV_APP.urls", namespace="CBV_APP")),  # CBV version
]

advanced_section/class_based_views/CBV_APP/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class School(models.Model):

    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self) -> str:
        return str(self.name)

    def get_absolute_url(self):
        return reverse("CBV_APP:detail", kwargs={"pk": self.pk})


class Student(models.Model):

    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(
        School, related_name="students", on_delete=models.CASCADE
    )

    def __str__(self) -> str:
        return str(self.name)

advanced_section/class_based_views/CBV_APP/views.py
from typing import Any, Dict

from CBV_APP.models import School, Student
from django.shortcuts import HttpResponse, render
from django.urls import reverse, reverse_lazy

# Create your views here.
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
    View,
)

""" # Function based views 
def index(request):
    return render(request, "index.html")
 """


"""
# View Class based Response
class CBView(View):
    def get(self, request):
        return HttpResponse(
            ""<head><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous"></head>
              <div class='container'><h1>Class based vies example </h1></div>""
        )
 """


class IndexView(TemplateView):
    template_name = "index.html"


# ⭐ by default it will return school_list as variable to template to override use above
class SchoolListView(ListView):
    """This will provide all the list of all items"""

    # override default <model>_list(variable passed to template)
    context_object_name = "schools"

    model = School
    template_name = "school_list.html"


class SchoolDetailView(DetailView):
    """This will provide all the list of all items"""

    # DetailView returns lower case version of class to override it
    # we can use :-
    context_object_name = "school_detail"
    model = School
    template_name = "school_detail.html"


class SchoolCreateView(CreateView):
    fields = ("name", "principal", "location")
    model = School
    template_name = "school_form.html"


class SchoolUpdateView(UpdateView):
    fields = ("name", "principal")
    model = School
    template_name = "school_form.html"


class SchoolDeleteView(DeleteView):
    model = School
    success_url = reverse_lazy("CBV_APP:list")
    template_name = "school_confirm_delete.html"

advanced_section/class_based_views/CBV_APP/templates/app_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">
        <title>Base</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'CBV_APP:list' %}" class="navbar-brand">Schools</a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}" class="navbar-link">Admin</a>
                </li>
                <li>
                    <a href="{% url 'CBV_APP:list' %}" class="navbar-brand">Schools</a>
                </li>
            </ul>
        </nav>
        <div class="container">
            <div class="div"></div>
            {% block body_block %}
            {% endblock body_block %}
        </div>
    </body>
</html>

advanced_section/class_based_views/CBV_APP/templates/school_confirm_delete.html
{% extends 'app_base.html' %}
{% block body_block %}
    <h1>Delete {{ school.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete"/>
        <a href="{% url 'CBV_APP:detail' pk=school.pk %}">Cancel</a>
    </form>
{% endblock body_block %}

advanced_section/class_based_views/CBV_APP/templates/school_detail.html
{% extends 'app_base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to school details page</h1>
        <h2>School detaisl</h2>
        <p>School details:</p>
        <p>Name: {{ school_detail.name }}</p>
        <p>Principal: {{ school_detail.principal }}</p>
        <p>Location: {{ school_detail.location }}</p>
        <h3>Students:</h3>
        {% for student in school_detail.students.all %}
            <p>Student Name: {{ student.name }}</p>
            <p>Student Age: {{ student.age }}</p>
        {% endfor %}
    </div>
    <div class="container">
        <p>
            <a class="btn btn-warning"
               href="{% url 'CBV_APP:update' pk=school_detail.pk %}">update schoole details</a>
        </p>
    </div>
{% endblock body_block %}

advanced_section/class_based_views/CBV_APP/templates/school_form.html
<!DOCTYPE html>
{% extends 'app_base.html' %}
{% block body_block %}
    <h1>
        {% if not form.instance.pk %}
            Create School
        {% else %}
            Update School
        {% endif %}
    </h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="btn btn-primary"/>
    </form>
{% endblock body_block %}

advanced_section/class_based_views/CBV_APP/templates/school_list.html
{% extends 'app_base.html' %}
{% block body_block %}
    <h1>Welcome to list of all schools</h1>
    <ol>
        {% for school in schools %}
            <h2>
                <li>
                    <a href="{{ school.id }}">{{ school.name }}</a>
                </li>
            </h2>
        {% endfor %}
    </ol>
{% endblock body_block %}

advanced_section/class_based_views/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">
        <title>Base</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'CBV_APP:list' %}" class="navbar-brand">Schools</a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}" class="navbar-link">Admin</a>
                </li>
                <li>
                    <a href="{% url 'CBV_APP:list' %}" class="navbar-brand">Schools</a>
                </li>
            </ul>
        </nav>
        <div class="container">
            <div class="div"></div>
            {% block body_block %}
            {% endblock body_block %}
        </div>
    </body>
</html>

advanced_section/class_based_views/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Home page!</h1>
</div>
    
{% endblock body_block %}