fourth_project/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import include, path
from template_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("template_app/", include("template_app.urls")),
]

# dummy line to check if user is registerd as commit msg"

fourth_project/learning_templates/template_app/urls.py
from django.urls import re_path
from template_app import views

# Template tagging
app_name = "templates_app"


urlpatterns = [
    re_path(r"relative/$", views.relative, name="relative"),
    re_path(r"other/$", views.other, name="other"),
]

fourth_project/learning_templates/template_app/views.py
from django.shortcuts import render

# Create your views here.
APP = "templates_app"


def index(request):
    context = {
        "title": "my first djanog application",
        "footer": "Sanket Corp pvt",
        "footer_right": "THis is index in index page",
    }
    return render(request, f"{APP}/index.html", context=context)


def other(request):
    return render(request, f"{APP}/other.html")


def relative(request):
    return render(request, f"{APP}/relative_url_templates.html")

fourth_project/learning_templates/templates/templates_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="{% static 'template_app/main.css' %}" />
		<title>Document</title>
	</head>
	<body>
		<nav class="nav">
			<ul class="nav-items">
				<li class="nav-item">
					<a href="{% url 'index' %}" class="nav-link">Brand</a>
				</li>
				<li class="nav-item">
					<a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
				</li>
				<li class="nav-item">
					<a href="{% url 'templates_app:other' %}" class="nav-link">Other</a>
				</li>
				<li class="nav-item">
					<a href="#" class="nav-link">Fourth</a>
				</li>
			</ul>
		</nav>
		<div class="container">
			<div class="container-left"></div>
			<div class="container-mid">{% block body_block %} {% endblock %}</div>
			<div class="container-right"></div>
		</div>
		<footer>{% block footer_block %} {% endblock %}</footer>
	</body>
</html>

fourth_project/learning_templates/templates/templates_app/index.html
<!DOCTYPE html>
{% extends "templates_app/base.html" %}
{% load basic_tags %}
{% block body_block %}
    <h1>{{ title | upper }}</h1>
    <h2>This is an example of index page template inheritance</h2>
{% endblock body_block %}
{% block footer_block %}
    <h5 class="footer">
        <p>THis is index in index page</p>
        <p>{{ footer | upper }}</p>
        <p>{{ footer_right | special_replace:'in index page' }}</p>
    </h5>
{% endblock footer_block %}

fourth_project/learning_templates/templates/templates_app/other.html
<!DOCTYPE html>
{% extends "templates_app/base.html" %}
{% block body_block %}
    <h1>Welcome to other page</h1>
    <h2>This is an example of template inheritance</h2>
{% endblock %}
f

fourth_project/learning_templates/templates/templates_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>
	<body>
		<h1>Welcome to Relative URL Templates</h1>
		<a href="{% url 'templates_app:other' %}">other</a>
		<a href="{% url 'admin:index' %}">admin</a>
		<a href="{% url 'index' %}">Link to index</a>
	</body>
</html>